# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"kwargs2str": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://data_tool.gjx.me/"

git_url = "https://github.com/JunxinGao/data_tool/tree/master/"

def custom_doc_links(name): return None
